### ISSUE TITLE
Bundy fails to build with Python 3.4

### ISSUE THREAD

**Issue by tomaszmrugalski** [bundy-dns/bundy#6]
Using fresh installation on OS X 10.9.2. Python installed using homebrew.

$ python3.4 --version
Python 3.4.0
configure succeeds, then build fails:

Making all in dns
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in .
make[6]: Nothing to be done for `all-am'.
Making all in tests
Making all in testdata
/Library/Developer/CommandLineTools/usr/bin/make  all-am
make[8]: Nothing to be done for`all-am'.
Making all in .
make[7]: Nothing to be done for `all-am'.
Making all in python
Making all in .
  CXX      libbundy_pydnspp_la-name_python.lo
name_python.cc:610:1: error: missing field 'tp_finalize' initializer [-Werror,-Wmissing-field-initializers]
};
^
name_python.cc:665:1: error: missing field 'tp_finalize' initializer [-Werror,-Wmissing-field-initializers]
};
^
2 errors generated.
make[7]: **\* [libbundy_pydnspp_la-name_python.lo] Error 1
